version: '3'

services:
  qemu-single:
    build:
      context: ./
      dockerfile: ./qemu/Dockerfile.single
  qemu:
    build:
      context: ./
      dockerfile: ./qemu/Dockerfile
  qemu-efi:
    build:
      context: ./
      dockerfile: ./qemu/Dockerfile.efi
  qemu-pxe:
    build:
      context: ./
      dockerfile: ./qemu/Dockerfile.pxe
