version: '3'

services:
  qemu-single:
    build:
      context: ./
      dockerfile: ./qemu/Dockerfile.single
  qemu:
    build:
      context: ./
      dockerfile: ./qemu/Dockerfile
  qemu-efi:
    build:
      context: ./
      dockerfile: ./qemu/Dockerfile.efi
  tftpd:
    build:
      context: ./
      dockerfile: ./qemu/Dockerfile.tftpd
    networks:
      default:
      backend:
        ipv4_address: 192.168.252.5
  qemu-pxe:
    depends_on:
      - tftpd
    build:
      context: ./
      dockerfile: ./qemu/Dockerfile.pxe
    tty: true
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      default:
      backend:
        ipv4_address: 192.168.252.11
    volumes:
      - ./qemu/dhcpd.conf:/etc/dhcp/dhcpd.conf
      - ./qemu/pxe-cmd.sh:/pxe-cmd.sh

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.252.0/24
