version: '3'

services:
  qemu-single:
    build:
      context: ./
      dockerfile: ./qemu/Dockerfile.single
  qemu:
    build:
      context: ./
      dockerfile: ./qemu/Dockerfile
  qemu-efi:
    build:
      context: ./
      dockerfile: ./qemu/Dockerfile.efi
  qemu-pxe:
    build:
      context: ./
      dockerfile: ./qemu/Dockerfile.pxe
    tty: true
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - ./qemu/dhcpd.conf:/etc/dhcp/dhcpd.conf
      - ./qemu/pxe-cmd.sh:/pxe-cmd.sh
